// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU9ovsbiNOuI7zZjaGyEDfaS-eziJ6bfw',
    appId: '1:571799920963:web:67eb659f8191947cce4ff6',
    messagingSenderId: '571799920963',
    projectId: 'dreamjob-c2b93',
    authDomain: 'dreamjob-c2b93.firebaseapp.com',
    storageBucket: 'dreamjob-c2b93.firebasestorage.app',
    measurementId: 'G-HR5M2DM25V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCExSv_cWhNtwCOWMT17C1fUBfStUqhziM',
    appId: '1:571799920963:android:e4d62654dca0b00dce4ff6',
    messagingSenderId: '571799920963',
    projectId: 'dreamjob-c2b93',
    storageBucket: 'dreamjob-c2b93.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhjfEqnFu8kcV6mc90p1F4olBPFAPxCUI',
    appId: '1:571799920963:ios:ddab866727678f33ce4ff6',
    messagingSenderId: '571799920963',
    projectId: 'dreamjob-c2b93',
    storageBucket: 'dreamjob-c2b93.firebasestorage.app',
    iosBundleId: 'com.example.dreamJobFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhjfEqnFu8kcV6mc90p1F4olBPFAPxCUI',
    appId: '1:571799920963:ios:ddab866727678f33ce4ff6',
    messagingSenderId: '571799920963',
    projectId: 'dreamjob-c2b93',
    storageBucket: 'dreamjob-c2b93.firebasestorage.app',
    iosBundleId: 'com.example.dreamJobFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAU9ovsbiNOuI7zZjaGyEDfaS-eziJ6bfw',
    appId: '1:571799920963:web:e2442e7fa22a1802ce4ff6',
    messagingSenderId: '571799920963',
    projectId: 'dreamjob-c2b93',
    authDomain: 'dreamjob-c2b93.firebaseapp.com',
    storageBucket: 'dreamjob-c2b93.firebasestorage.app',
    measurementId: 'G-KLMJ6HZZMZ',
  );
}
